data: # root path of train/validation data (either relative/absoulte path is ok)
  train: 'train'
  validation: 'val'
---
train:
  rep_discriminator: 1
  num_workers: 32
  batch_size: 16
  optimizer: 'adam'
  epochs: 1500
  adam:
    init_lr: 0.0001
    final_lr: 0.00001
    beta1: 0.5
    beta2: 0.9
---
audio:
  n_mel_channels: 80
  segment_length: 16000
  pad_short: 2000
  filter_length: 1024
  hop_length: 256 # WARNING: this can't be changed.
  win_length: 1024
  sampling_rate: 22050
  mel_fmin: 0.0
  mel_fmax: 8000.0
---
model:
  feat_match: 10.0
---
log:
  summary_interval: 1
  validation_interval: 50
  save_interval: 25
  chkpt_dir: 'chkpt'
  log_dir: 'logs'
